# Generated by Django 5.2.7 on 2025-10-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('tea', 'Tea'), ('coffee', 'Coffee'), ('cocktail', 'Cocktail')], max_length=20)),
                ('description', models.TextField()),
                ('moods', models.JSONField(default=list)),
                ('weather', models.JSONField(default=list)),
                ('time_of_day', models.JSONField(default=list)),
                ('season', models.JSONField(default=list)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
